In [2]:
import numpy as np

In [32]:
a = np.arange(10)
b = a[2:6]
print(a, b)
b[:] = np.arange(30, 34)
print(a, b)

[0 1 2 3 4 5 6 7 8 9] [2 3 4 5]
[ 0  1 30 31 32 33  6  7  8  9] [30 31 32 33]


In [38]:
x, y = np.mgrid[range(0, 5), 0:5]
print(x, y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]] [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [48]:
r = np.random.rand(5, 5)

In [60]:
print(np.diag(range(0, 5), 0))
print(np.diag(range(0, 4), 1))

print(r)
np.diag(np.diag(r, 3), 1)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]]
[[0.5155795  0.90119392 0.81240214 0.12585162 0.44731033]
 [0.74299482 0.90647049 0.10548208 0.3345664  0.45972784]
 [0.41599199 0.16464412 0.08721425 0.23023423 0.48298071]
 [0.16017459 0.82653423 0.53000838 0.06431578 0.24636748]
 [0.97027235 0.76195503 0.24794184 0.17916051 0.35018087]]


array([[0.        , 0.12585162, 0.        ],
       [0.        , 0.        , 0.45972784],
       [0.        , 0.        , 0.        ]])

In [64]:
print(np.zeros(10))

print(np.ones((5,5)))

print(np.eye(4))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Считывание из файла


In [66]:
data = np.genfromtxt('filename.dat')


OSError: filename.dat not found.

In [86]:
a = np.array(['Мцыри', 'Преступление и наказание', 'Кортик', 'Бородино', 'Молодая гвардия', 'Евгений Онегин', 'Герой нашего времени', 'Идиот', 'Зойкина квартира', 'Демон', 'Собачье Сердце', 'Сборник романов Достоевского', 'Стихотворения Лермонтова',
         'Белая гвардия', 'Мастер и Маргарита', 'Лучшие произведения М.Ю. Лермонтова', 'Горячий снег', 'Дикая собака Динго', 'Беглец', 'Стихотворения Пушкина', 'Василий Теркин', 'Выхожу один я на дорогу', 'Война и Мир', 'Анна Каренина', 'Кинжал',
         'Севастопольские рассказы', 'Бал', 'Ангел', 'Романы Толстого', 'Князь Серебряный','Сердца Трех','По Ком Звонит Колокол', 'Марк Твен', 'Малыш и Карлсон', 'Великий Гетсби', 'Маугли',
         'Мио, Мой Мио', 'На западном фронте без перемен', 'Портрет Дориана Грея', 'Мартин Иден', 'Собор Парижской Богоматери', 'Отверженные', 'Белый Клык', 'Человек, который смеется', 'Детективы Агаты Кристи',
         'Фауст', 'Лучшие стихотворения Киплинга', 'Рубаи Омара Хайяма', 'Сонеты Уильяма Шекспира', 'Гомер: Иллиада', 'Гомер: Одиссея', 'Ворон', 'Уильям Блейк',
         'Гораций', 'Басё', 'Сборник стихотворений Гёте', 'Шиллер. Избраннные произведения', 'Сайгё', 'Сборник Роберта Бернса', 'Омар Хайям'])

size = a.shape[0]
lBooks = a[size//2:size-size//4][::3]
print(lBooks)

['Сердца Трех' 'Малыш и Карлсон' 'Мио, Мой Мио' 'Мартин Иден' 'Белый Клык']
